### PR TITLE
Downloading a specific certificate content

### PR DESCRIPTION
**Pull request by abunashir**
This commit implement the certificate content retrieving interface, but there are still some part that are not clear yet, like what is the approach to download a certificate, what sort of functionality we want to allow through this interface and also do we write the content or just return it, and also something with the file path

### CODE REVIEW

**Comment by abunashir** [comment]
@ronaldtse on the `digicert order reissue --order-id 12345 --fetch --output /tmp/certs/12345`, do we need the `--fetch` option separately? I feel like whenever anyone is specifying the `output` option then we will need to `fetch` the certificate before writing it to the output path, so, I was considering to simplify this and use only the `output` option, what do you think?

**Comment by ronaldtse** [comment]
@abunashir sure let's assume "to fetch" when `--output` is present!

**Comment by ronaldtse** [comment]
@abunashir are we going to rebase this and merge, or do you have other plans? Thanks.

**Comment by abunashir** [comment]
@ronaldtse: We are not going to use this PR, we already added the certificate downloading in an another PR, but I am keeping it open for now. The interfaces we described here is not fully implemented, but I will close this one as soon as we have done it.  Thanks.

**Comment by abunashir** [comment]
@ronaldtse: Regarding the `certificate list` interface, One order instance returns only one certificate, so I was thinking should we use `certificate find` like we are doing for an `order` and that will return the details of the certificate and use flag it can be filtered down to `id` or even download it to path?

**Comment by ronaldtse** [comment]
Agree, we can call it 'certificate fetch' to indicate that it only returns one. Thanks @abunashir !

**Comment by abunashir** [comment]
@ronaldtse : Finally! all the interfaces are implemented and we are not going to use this one, so closing it now :)

**Pull request closed without merging**
